# Generated by Django 5.0.7 on 2024-07-23 13:21

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def forwards_func(apps, schema_editor):
    Cert = apps.get_model("governanceplatform", "Cert")
    CertTranslation = apps.get_model("governanceplatform", "CertTranslation")

    for object in Cert.objects.all():
        CertTranslation.objects.create(
            master_id=object.pk,
            language_code="en",
            name=object.temp_name,
            full_name=object.temp_full_name,
            description=object.temp_description,
        )


def backwards_func(apps, schema_editor):
    Cert = apps.get_model("governanceplatform", "Cert")
    CertTranslation = apps.get_model("governanceplatform", "RegulatorTranslation")

    for object in Cert.objects.all():
        translation = _get_translation(object, CertTranslation)
        object.name = translation.name
        object.full_name = translation.full_name
        object.description = translation.description
        object.save()


def _get_translation(object, CertTranslation):
    translations = CertTranslation.objects.filter(master_id=object.pk)
    try:
        return translations.get(language_code="en")
    except ObjectDoesNotExist:
        return translations.get()


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0012_remove_cert_description_remove_cert_full_name_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
